[2025-02-05T04:17:35.869+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dag.execute_remote_script manual__2025-02-05T04:12:31.144593+00:00 [queued]>
[2025-02-05T04:17:35.872+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dag.execute_remote_script manual__2025-02-05T04:12:31.144593+00:00 [queued]>
[2025-02-05T04:17:35.872+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-05T04:17:35.876+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): execute_remote_script> on 2025-02-05 04:12:31.144593+00:00
[2025-02-05T04:17:35.878+0000] {standard_task_runner.py:57} INFO - Started process 244 to run task
[2025-02-05T04:17:35.880+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_dag', 'execute_remote_script', 'manual__2025-02-05T04:12:31.144593+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpei8t7qyc']
[2025-02-05T04:17:35.882+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask execute_remote_script
[2025-02-05T04:17:35.889+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-05T04:17:35.901+0000] {task_command.py:415} INFO - Running <TaskInstance: example_dag.execute_remote_script manual__2025-02-05T04:12:31.144593+00:00 [running]> on host 3849bfb82152
[2025-02-05T04:17:35.937+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_dag' AIRFLOW_CTX_TASK_ID='execute_remote_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T04:12:31.144593+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T04:12:31.144593+00:00'
[2025-02-05T04:17:35.938+0000] {ssh.py:135} INFO - Creating ssh_client
[2025-02-05T04:17:35.960+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-02-05T04:17:35.967+0000] {base.py:73} INFO - Using connection ID 'ssh-server' for task execution.
[2025-02-05T04:17:35.967+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-02-05T04:17:36.002+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2025-02-05T04:17:36.059+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2025-02-05T04:17:36.059+0000] {ssh.py:475} INFO - Running command: bash /script/date_print.sh
[2025-02-05T04:17:36.154+0000] {ssh.py:521} INFO - 当前时间是: Wed Feb  5 04:17:36 UTC 2025
[2025-02-05T04:17:36.169+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_dag, task_id=execute_remote_script, execution_date=20250205T041231, start_date=20250205T041735, end_date=20250205T041736
[2025-02-05T04:17:36.185+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-05T04:17:36.193+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
